#!/usr/bin/env python3
"""Apply reviewed FruitySelia UI translations after xcstringstool source sync."""
import json
from pathlib import Path

catalog_path = Path(__file__).parents[1] / "SeliaScan/Resources/Localizable.xcstrings"
translations = {
    "%@": ("%@", "%@", "%@", "%@"),
    "%@ pages · %@": ("%1$@ stránek · %2$@", "%1$@ Seiten · %2$@", "%1$@ páginas · %2$@", "%1$@ 页 · %2$@"),
    "%@°": ("%@°", "%@°", "%@°", "%@°"),
    "A scan can contain at most 20 pages.": ("Sken může obsahovat nejvýše 20 stránek.", "Ein Scan darf höchstens 20 Seiten enthalten.", "Un escaneo puede contener como máximo 20 páginas.", "一次扫描最多可包含 20 页。"),
    "A scan must contain between 1 and 20 pages.": ("Sken musí obsahovat 1 až 20 stránek.", "Ein Scan muss 1 bis 20 Seiten enthalten.", "Un escaneo debe contener entre 1 y 20 páginas.", "扫描必须包含 1 到 20 页。"),
    "A source page is too large to process safely.": ("Zdrojová stránka je příliš velká pro bezpečné zpracování.", "Eine Quellseite ist für die sichere Verarbeitung zu groß.", "Una página de origen es demasiado grande para procesarla de forma segura.", "源页面过大，无法安全处理。"),
    "Allow FruitySelia to add images to Photos, then try again.": ("Povolte FruitySelia přidávat obrázky do Fotek a zkuste to znovu.", "Erlaube FruitySelia, Bilder zu Fotos hinzuzufügen, und versuche es erneut.", "Permite que FruitySelia añada imágenes a Fotos y vuelve a intentarlo.", "请允许 FruitySelia 将图像添加到照片，然后重试。"),
    "%arg/%arg": ("%1$arg/%2$arg", "%1$arg/%2$arg", "%1$arg/%2$arg", "%1$arg/%2$arg"),
    "Ask Every Time": ("Vždy se zeptat", "Jedes Mal fragen", "Preguntar siempre", "每次询问"),
    "Automatic Folder": ("Automatická složka", "Automatischer Ordner", "Carpeta automática", "自动文件夹"),
    "Auto": ("Automaticky", "Automatisch", "Automático", "自动"),
    "Black & White": ("Černobíle", "Schwarzweiß", "Blanco y negro", "黑白"),
    "Brightness": ("Jas", "Helligkeit", "Brillo", "亮度"),
    "Color": ("Barva", "Farbe", "Color", "彩色"),
    "Contrast": ("Kontrast", "Kontrast", "Contraste", "对比度"),
    "Edit Page": ("Upravit stránku", "Seite bearbeiten", "Editar página", "编辑页面"),
    "Edit page": ("Upravit stránku", "Seite bearbeiten", "Editar página", "编辑页面"),
    "Filter": ("Filtr", "Filter", "Filtro", "滤镜"),
    "Grayscale": ("Stupně šedi", "Graustufen", "Escala de grises", "灰度"),
    "Rotate Left": ("Otočit doleva", "Nach links drehen", "Girar a la izquierda", "向左旋转"),
    "Rotate Right": ("Otočit doprava", "Nach rechts drehen", "Girar a la derecha", "向右旋转"),
    "Saturation": ("Sytost", "Sättigung", "Saturación", "饱和度"),
    "Shadows": ("Stíny", "Schatten", "Sombras", "阴影"),
    "%arg": ("%arg", "%arg", "%arg", "%arg"),
    "%arg pages · %arg": ("%1$arg stránek · %2$arg", "%1$arg Seiten · %2$arg", "%1$arg páginas · %2$arg", "%1$arg 页 · %2$arg"),
    "%arg°": ("%arg°", "%arg°", "%arg°", "%arg°"),
    "Actions": ("Akce", "Aktionen", "Acciones", "操作"),
    "Advanced": ("Pokročilé", "Erweitert", "Avanzado", "高级"),
    "Apply": ("Použít", "Anwenden", "Aplicar", "应用"),
    "Balanced": ("Vyvážená", "Ausgewogen", "Equilibrado", "均衡"),
    "Brush": ("Štětec", "Pinsel", "Pincel", "画笔"),
    "Brush size": ("Velikost štětce", "Pinselgröße", "Tamaño del pincel", "画笔大小"),
    "Cancel": ("Zrušit", "Abbrechen", "Cancelar", "取消"),
    "Clear": ("Vymazat", "Löschen", "Borrar", "清除"),
    "Clear Folder": ("Zrušit složku", "Ordner entfernen", "Quitar carpeta", "清除文件夹"),
    "Codes on this page": ("Kódy na této stránce", "Codes auf dieser Seite", "Códigos de esta página", "本页代码"),
    "Copy": ("Kopírovat", "Kopieren", "Copiar", "复制"),
    "Choose Folder": ("Vybrat složku", "Ordner auswählen", "Elegir carpeta", "选择文件夹"),
    "Cleaning…": ("Čištění…", "Bereinigung…", "Limpiando…", "正在清理…"),
    "Could not archive scanned page.": ("Naskenovanou stránku se nepodařilo uložit.", "Die gescannte Seite konnte nicht archiviert werden.", "No se pudo archivar la página escaneada.", "无法归档扫描页面。"),
    "Could not create the PDF.": ("PDF se nepodařilo vytvořit.", "Die PDF-Datei konnte nicht erstellt werden.", "No se pudo crear el PDF.", "无法创建 PDF。"),
    "Default Image Folder": ("Výchozí složka obrázků", "Standardordner für Bilder", "Carpeta de imágenes predeterminada", "默认图像文件夹"),
    "Default PDF Folder": ("Výchozí složka PDF", "Standardordner für PDF", "Carpeta PDF predeterminada", "默认 PDF 文件夹"),
    "Delete": ("Smazat", "Löschen", "Eliminar", "删除"),
    "Delete exact saved output": ("Smazat přesně tento uložený výstup", "Genau diese gespeicherte Ausgabe löschen", "Eliminar exactamente esta salida guardada", "删除此确切的已存输出"),
    "Delete this exact saved output?": ("Smazat přesně tento uložený výstup?", "Genau diese gespeicherte Ausgabe löschen?", "¿Eliminar exactamente esta salida guardada?", "删除此确切的已存输出？"),
    "Delete saved mark?": ("Smazat uloženou značku?", "Gespeicherte Markierung löschen?", "¿Eliminar la marca guardada?", "删除已保存的标记？"),
    "Delete Saved Mark": ("Smazat uloženou značku", "Gespeicherte Markierung löschen", "Eliminar marca guardada", "删除已保存的标记"),
    "Document scanning is not available on this device.": ("Skenování dokumentů není na tomto zařízení dostupné.", "Das Scannen von Dokumenten ist auf diesem Gerät nicht verfügbar.", "El escaneo de documentos no está disponible en este dispositivo.", "此设备无法扫描文稿。"),
    "Deleted or missing": ("Smazáno nebo chybí", "Gelöscht oder fehlt", "Eliminado o no encontrado", "已删除或缺失"),
    "Done": ("Hotovo", "Fertig", "Listo", "完成"),
    "Drag to move. Pinch to resize and rotate.": ("Přetažením posuňte. Sevřením změňte velikost a otočení.", "Zum Verschieben ziehen. Zum Skalieren und Drehen aufziehen.", "Arrastra para mover. Pellizca para cambiar el tamaño y girar.", "拖动以移动。捏合以调整大小和旋转。"),
    "Editing": ("Úpravy", "Bearbeitung", "Edición", "编辑"),
    "Email subject": ("Předmět e-mailu", "E-Mail-Betreff", "Asunto del correo", "邮件主题"),
    "Export": ("Export", "Export", "Exportar", "导出"),
    "Extract all text": ("Extrahovat všechen text", "Gesamten Text extrahieren", "Extraer todo el texto", "提取全部文本"),
    "Extracted Text": ("Extrahovaný text", "Extrahierter Text", "Texto extraído", "提取的文本"),
    "File Details": ("Podrobnosti souboru", "Dateidetails", "Detalles del archivo", "文件详情"),
    "File name": ("Název souboru", "Dateiname", "Nombre del archivo", "文件名"),
    "Files": ("Soubory", "Dateien", "Archivos", "文件"),
    "Format": ("Formát", "Format", "Formato", "格式"),
    "General": ("Obecné", "Allgemein", "General", "通用"),
    "High": ("Vysoká", "Hoch", "Alta", "高"),
    "Images": ("Obrázky", "Bilder", "Imágenes", "图像"),
    "Image": ("Obrázek", "Bild", "Imagen", "图像"),
    "Import Stamp": ("Importovat razítko", "Stempel importieren", "Importar sello", "导入印章"),
    "Import": ("Importovat", "Importieren", "Importar", "导入"),
    "JPEG": ("JPEG", "JPEG", "JPEG", "JPEG"),
    "Kilobytes": ("Kilobajty", "Kilobyte", "Kilobytes", "千字节"),
    "Manual cleanup": ("Ruční čištění", "Manuelle Bereinigung", "Limpieza manual", "手动清理"),
    "Manual Position": ("Ruční umístění", "Manuelle Position", "Posición manual", "手动位置"),
    "Horizontal Position": ("Vodorovná poloha", "Horizontale Position", "Posición horizontal", "水平位置"),
    "Vertical Position": ("Svislá poloha", "Vertikale Position", "Posición vertical", "垂直位置"),
    "New Scan": ("Nové skenování", "Neuer Scan", "Nuevo escaneo", "新建扫描"),
    "No QR codes or barcodes found": ("Nebyly nalezeny žádné QR ani čárové kódy", "Keine QR- oder Barcodes gefunden", "No se encontraron códigos QR ni de barras", "未找到二维码或条形码"),
    "No scan": ("Žádný sken", "Kein Scan", "Sin escaneo", "无扫描"),
    "No saved signature or stamp yet.": ("Zatím není uložen žádný podpis ani razítko.", "Noch keine Unterschrift oder kein Stempel gespeichert.", "Aún no hay ninguna firma ni sello guardado.", "尚未保存签名或印章。"),
    "OCR: English, Czech, German, Spanish, Simplified Chinese": ("OCR: angličtina, čeština, němčina, španělština, zjednodušená čínština", "OCR: Englisch, Tschechisch, Deutsch, Spanisch, vereinfachtes Chinesisch", "OCR: inglés, checo, alemán, español, chino simplificado", "OCR：英语、捷克语、德语、西班牙语、简体中文"),
    "OK": ("OK", "OK", "Aceptar", "好"),
    "Open %arg": ("Otevřít %arg", "%arg öffnen", "Abrir %arg", "打开 %arg"),
    "Opening scanner…": ("Otevírání skeneru…", "Scanner wird geöffnet…", "Abriendo el escáner…", "正在打开扫描仪…"),
    "Open full-screen viewer": ("Otevřít zobrazení na celou obrazovku", "Vollbildansicht öffnen", "Abrir visor de pantalla completa", "打开全屏查看器"),
    "Original": ("Originál", "Original", "Original", "原始"),
    "PDF": ("PDF", "PDF", "PDF", "PDF"),
    "PDF and image destinations are selected with Files": ("Cíle PDF a obrázků se vybírají v Souborech", "PDF- und Bildziele werden über Dateien ausgewählt", "Los destinos de PDF e imágenes se eligen con Archivos", "使用“文件”选择 PDF 和图像位置"),
    "PNG": ("PNG", "PNG", "PNG", "PNG"),
    "Page %arg of %arg": ("Stránka %1$arg z %2$arg", "Seite %1$arg von %2$arg", "Página %1$arg de %2$arg", "第 %1$arg 页，共 %2$arg 页"),
    "Page %arg": ("Stránka %arg", "Seite %arg", "Página %arg", "第 %arg 页"),
    "Page %@ of %@": ("Stránka %1$@ z %2$@", "Seite %1$@ von %2$@", "Página %1$@ de %2$@", "第 %1$@ 页，共 %2$@ 页"),
    "Page %@": ("Stránka %@", "Seite %@", "Página %@", "第 %@ 页"),
    "Pages are processed on-device": ("Stránky se zpracovávají v zařízení", "Seiten werden auf dem Gerät verarbeitet", "Las páginas se procesan en el dispositivo", "页面在设备上处理"),
    "Photos": ("Fotky", "Fotos", "Fotos", "照片"),
    "Preparing PDF…": ("Příprava PDF…", "PDF wird vorbereitet…", "Preparando PDF…", "正在准备 PDF…"),
    "Print": ("Tisk", "Drucken", "Imprimir", "打印"),
    "Privacy": ("Soukromí", "Datenschutz", "Privacidad", "隐私"),
    "Protect Recent Scans": ("Chránit nedávné skeny", "Letzte Scans schützen", "Proteger escaneos recientes", "保护最近扫描"),
    "Read all pages": ("Přečíst všechny stránky", "Alle Seiten vorlesen", "Leer todas las páginas", "朗读所有页面"),
    "Ready to scan": ("Připraveno ke skenování", "Bereit zum Scannen", "Listo para escanear", "准备扫描"),
    "Readable PDF is %arg; selected target could not be met.": ("Čitelné PDF má %arg; vybraného cíle nešlo dosáhnout.", "Die lesbare PDF ist %arg groß; das gewählte Ziel konnte nicht erreicht werden.", "El PDF legible ocupa %arg; no se pudo alcanzar el objetivo elegido.", "可读 PDF 大小为 %arg；无法达到所选目标。"),
    "Recent": ("Nedávné", "Zuletzt", "Recientes", "最近"),
    "Recent scans are unavailable.": ("Nedávné skeny nejsou dostupné.", "Letzte Scans sind nicht verfügbar.", "Los escaneos recientes no están disponibles.", "最近扫描不可用。"),
    "Reorder Pages": ("Změnit pořadí stránek", "Seiten neu anordnen", "Reordenar páginas", "重新排列页面"),
    "Reorder pages": ("Změnit pořadí stránek", "Seiten neu anordnen", "Reordenar páginas", "重新排列页面"),
    "Redact": ("Začernit", "Schwärzen", "Ocultar", "涂黑"),
    "Redo": ("Znovu", "Wiederholen", "Rehacer", "重做"),
    "Rescan": ("Skenovat znovu", "Erneut scannen", "Volver a escanear", "重新扫描"),
    "Result": ("Výsledek", "Ergebnis", "Resultado", "结果"),
    "Rotation": ("Otočení", "Drehung", "Rotación", "旋转"),
    "Save": ("Uložit", "Sichern", "Guardar", "保存"),
    "Save Images to Files": ("Uložit obrázky do Souborů", "Bilder in Dateien sichern", "Guardar imágenes en Archivos", "将图像存储到文件"),
    "Save Images to Photos": ("Uložit obrázky do Fotek", "Bilder in Fotos sichern", "Guardar imágenes en Fotos", "将图像存储到照片"),
    "Save PDF to Files": ("Uložit PDF do Souborů", "PDF in Dateien sichern", "Guardar PDF en Archivos", "将 PDF 存储到文件"),
    "Save signature for reuse": ("Uložit podpis pro další použití", "Unterschrift zur Wiederverwendung sichern", "Guardar firma para reutilizar", "保存签名以便重复使用"),
    "Save mark for reuse": ("Uložit značku pro další použití", "Markierung zur Wiederverwendung sichern", "Guardar marca para reutilizar", "保存标记以便重复使用"),
    "Saved": ("Uloženo", "Gesichert", "Guardado", "已保存"),
    "Saved %arg image(s) to Photos.": ("Do Fotek bylo uloženo obrázků: %arg.", "%arg Bild(er) wurden in Fotos gesichert.", "Se guardaron %arg imagen(es) en Fotos.", "已将 %arg 张图像存储到照片。"),
    "Saved %arg image(s).": ("Uloženo obrázků: %arg.", "%arg Bild(er) gesichert.", "Se guardaron %arg imagen(es).", "已存储 %arg 张图像。"),
    "Saved PDF to %arg.": ("PDF bylo uloženo jako %arg.", "PDF wurde als %arg gesichert.", "El PDF se guardó como %arg.", "PDF 已存储为 %arg。"),
    "Saved outputs": ("Uložené výstupy", "Gesicherte Ausgaben", "Salidas guardadas", "已存输出"),
    "Saved Signatures and Stamps": ("Uložené podpisy a razítka", "Gespeicherte Unterschriften und Stempel", "Firmas y sellos guardados", "已保存的签名和印章"),
    "Saving": ("Ukládání", "Sichern", "Guardado", "存储"),
    "Scan Document": ("Skenovat dokument", "Dokument scannen", "Escanear documento", "扫描文稿"),
    "Scan cancelled.": ("Skenování bylo zrušeno.", "Scannen abgebrochen.", "Escaneo cancelado.", "扫描已取消。"),
    "Scan Stamp": ("Naskenovat razítko", "Stempel scannen", "Escanear sello", "扫描印章"),
    "Scan → save → share": ("Skenovat → uložit → sdílet", "Scannen → sichern → teilen", "Escanear → guardar → compartir", "扫描 → 存储 → 共享"),
    "Scanned page": ("Naskenovaná stránka", "Gescannte Seite", "Página escaneada", "扫描页面"),
    "Scanning": ("Skenování", "Scannen", "Escaneo", "扫描"),
    "Searchable text is included when OCR succeeds.": ("Při úspěšném OCR se přidá prohledávatelný text.", "Bei erfolgreicher OCR wird durchsuchbarer Text hinzugefügt.", "Se incluye texto buscable cuando el OCR tiene éxito.", "OCR 成功时会包含可搜索文本。"),
    "Secure redaction": ("Bezpečné začernění", "Sichere Schwärzung", "Ocultación segura", "安全涂黑"),
    "Select a scan": ("Vyberte sken", "Scan auswählen", "Selecciona un escaneo", "选择扫描"),
    "FruitySelia": ("FruitySelia", "FruitySelia", "FruitySelia", "FruitySelia"),
    "FruitySelia sample page": ("Ukázková stránka FruitySelia", "FruitySelia-Beispielseite", "Página de ejemplo de FruitySelia", "FruitySelia 示例页面"),
    "FruitySelia no longer has access to this location.": ("FruitySelia už k tomuto umístění nemá přístup.", "FruitySelia hat keinen Zugriff mehr auf diesen Speicherort.", "FruitySelia ya no tiene acceso a esta ubicación.", "FruitySelia 已无法访问此位置。"),
    "Settings": ("Nastavení", "Einstellungen", "Ajustes", "设置"),
    "Share": ("Sdílet", "Teilen", "Compartir", "共享"),
    "Share Images": ("Sdílet obrázky", "Bilder teilen", "Compartir imágenes", "共享图像"),
    "Share PDF": ("Sdílet PDF", "PDF teilen", "Compartir PDF", "共享 PDF"),
    "Share PDF + Images": ("Sdílet PDF + obrázky", "PDF + Bilder teilen", "Compartir PDF + imágenes", "共享 PDF + 图像"),
    "Sharing": ("Sdílení", "Teilen", "Compartir", "共享"),
    "Sign / Stamp": ("Podpis / razítko", "Unterschrift / Stempel", "Firma / sello", "签名 / 印章"),
    "Signature drawing area": ("Plocha pro kreslení podpisu", "Zeichenfläche für Unterschrift", "Área para dibujar la firma", "签名绘制区域"),
    "Signature or stamp preview": ("Náhled podpisu nebo razítka", "Vorschau der Unterschrift oder des Stempels", "Vista previa de firma o sello", "签名或印章预览"),
    "Size": ("Velikost", "Größe", "Tamaño", "大小"),
    "Small": ("Malá", "Klein", "Pequeño", "小"),
    "Straight line": ("Rovná čára", "Gerade Linie", "Línea recta", "直线"),
    "Smart cleanup": ("Chytré čištění", "Intelligente Bereinigung", "Limpieza inteligente", "智能清理"),
    "Target size": ("Cílová velikost", "Zielgröße", "Tamaño objetivo", "目标大小"),
    "The exact saved file could not be identified.": ("Přesný uložený soubor se nepodařilo určit.", "Die genaue gesicherte Datei konnte nicht bestimmt werden.", "No se pudo identificar el archivo guardado exacto.", "无法识别确切的已存文件。"),
    "The image could not be rendered.": ("Obrázek se nepodařilo vykreslit.", "Das Bild konnte nicht gerendert werden.", "No se pudo renderizar la imagen.", "无法渲染图像。"),
    "The page could not be analyzed.": ("Stránku se nepodařilo analyzovat.", "Die Seite konnte nicht analysiert werden.", "No se pudo analizar la página.", "无法分析页面。"),
    "The saved file was moved or deleted.": ("Uložený soubor byl přesunut nebo smazán.", "Die gesicherte Datei wurde verschoben oder gelöscht.", "El archivo guardado se movió o eliminó.", "已存文件已被移动或删除。"),
    "The saved folder permission expired. Choose the folder again.": ("Oprávnění k uložené složce vypršelo. Vyberte ji znovu.", "Die Berechtigung für den Ordner ist abgelaufen. Wähle ihn erneut aus.", "El permiso de la carpeta guardada caducó. Elige la carpeta de nuevo.", "已存文件夹权限已过期。请重新选择文件夹。"),
    "The saved signature or stamp is missing.": ("Uložený podpis nebo razítko chybí.", "Die gespeicherte Unterschrift oder der Stempel fehlt.", "Falta la firma o el sello guardado.", "已保存的签名或印章缺失。"),
    "The selected signature or stamp has no usable ink.": ("Vybraný podpis nebo razítko neobsahuje použitelnou kresbu.", "Die ausgewählte Unterschrift oder der Stempel enthält keine verwendbare Markierung.", "La firma o el sello seleccionado no contiene trazos utilizables.", "所选签名或印章没有可用笔迹。"),
    "Private, on-device document scan": ("Soukromý sken dokumentu zpracovaný v zařízení", "Privater, auf dem Gerät verarbeiteter Dokumentenscan", "Escaneo privado procesado en el dispositivo", "在设备上处理的私密文稿扫描"),
    "This scan is incomplete and was skipped.": ("Tento sken je neúplný a byl přeskočen.", "Dieser Scan ist unvollständig und wurde übersprungen.", "Este escaneo está incompleto y se omitió.", "此扫描不完整，已跳过。"),
    "Text": ("Text", "Text", "Texto", "文本"),
    "Thickness": ("Tloušťka", "Stärke", "Grosor", "粗细"),
    "Tool": ("Nástroj", "Werkzeug", "Herramienta", "工具"),
    "This adds only a visual signature or stamp. It does not verify identity or document integrity.": ("Tímto se přidá pouze vizuální podpis nebo razítko. Neověřuje totožnost ani neporušenost dokumentu.", "Dies fügt nur eine sichtbare Unterschrift oder einen Stempel hinzu. Identität und Dokumentintegrität werden nicht bestätigt.", "Esto solo añade una firma o un sello visual. No verifica la identidad ni la integridad del documento.", "这只会添加可视签名或印章，不会验证身份或文档完整性。"),
    "Undo": ("Zpět", "Rückgängig", "Deshacer", "撤销"),
    "Use Drawing": ("Použít kresbu", "Zeichnung verwenden", "Usar dibujo", "使用绘图"),
    "You can save up to 12 signatures and stamps.": ("Můžete uložit nejvýše 12 podpisů a razítek.", "Du kannst bis zu 12 Unterschriften und Stempel speichern.", "Puedes guardar hasta 12 firmas y sellos.", "最多可保存 12 个签名和印章。"),
    "Each scan can override these folders in File Details.": ("Každý sken může tyto složky změnit v Podrobnostech souboru.", "Jeder Scan kann diese Ordner in den Dateidetails überschreiben.", "Cada escaneo puede cambiar estas carpetas en Detalles del archivo.", "每次扫描都可在文件详情中覆盖这些文件夹。"),
}

catalog = json.loads(catalog_path.read_text())
languages = ("cs", "de", "es", "zh-Hans")
missing = set(catalog["strings"]) - set(translations)
if missing:
    raise SystemExit(f"Missing reviewed translations: {sorted(missing)}")
for key, values in translations.items():
    entry = catalog["strings"].setdefault(key, {})
    localized = entry.setdefault("localizations", {})
    for language, value in zip(languages, values):
        localized[language] = {"stringUnit": {"state": "translated", "value": value}}
catalog_path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
